--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,4 @@
 PROGNAME=readsb
-READSB_VERSION := "$(shell echo -n 'wiedehopf git: '; git describe --abbrev --dirty --always; git show -s --format=format:"(committed: %cd)" | tr -cd '[a-z],[A-Z],[0-9],:, ,\-,_,(,)')"
 
 RTLSDR ?= no
 BLADERF ?= no
