---
name: Build
'on':
  push:
    branches:
      - main
    paths-ignore:
      - .dockerignore
      - .github/dependabot.yml
      - .gitignore
      - Dockerfile
      - 'docs/**'
      - '**/CODEOWNERS'
      - '**/README*'
  workflow_dispatch:
    inputs:
      paths:
        description: List of paths where to look for RPM specs
        required: false

jobs:
  packages:
    name: Build RPM packages and publish repo updates
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build packages
        run: ./build.sh ${{ inputs.paths }}
      - name: Update repodata
        run: ./updaterepo.sh
      - name: Push updates
        run: |
          git config gc.auto 0
          git config --global push.default simple
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all docs
          git commit -m "Update packages and repodata"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
